### ISSUE TITLE
ゲームデータのパース処理の一元化とマージ時優先度

### ISSUE THREAD

**Issue by kanomiya** [kanomiya/Picket#1]
### 作業
- 作業1：パース時に完全統合ファイルのルートを起点にする（一元化：メソッド一本ですべてのパースが完了する）
  - 完全統合ファイル：ゲームディレクトリのルートを起点にした統合ファイル
- 作業2：統合ファイル/個別ファイルのマージ時の個別優先度処理
### 経緯

Picketでは、ゲームを単一のDSL（Data Serialization Language/データ直列化言語=データ記述言語）ファイルのみで表現することが可能であるようにする。
だが、特に手作業でDSLを書く、扱う場合、一ファイルが冗長になり扱いにくくなることが考えられる。例えば、次の場合である。
- 特定の要素を瞬時に見つけることが難しくなる
  - 一般的なディスプレイでは、ファイル内容が一画面内に収まらない可能性がある、高い
  - キー（プロパティ名）の重複が増え、検索を使ってもすぐにたどり着けない

この問題を解決するため、（Webサーバー/HTMLのような）フォルダ構造を利用したファイル分割を行いたい。
具体例は末尾に記す。

ファイル分割を行った後も、分割前のファイル（統合ファイル）と分割後のファイル群（分割ファイル）とは同一の意味を持つはずであり、分割ファイルをまとめることで統合ファイルと同じ表現を作りだしてからパースすることでパース部の一元化が見込める（作業1）。

また、統合ファイルと分割ファイルが併存する状態にも過剰な分割（ファイルの散乱）を防ぐことができる点で価値があると考える。しかしこの状態においては、マージ（統合）時にどちらを優先するかを個別に考える必要がある点に留意しなければならない（作業2）。
### 具体例

統合されたファイル
- data.yaml

分割されたファイル群
- students
  - Atsushi.yaml
  - Honoka.yaml
- teachers
  - Jun.yaml
  - Riko.yaml

data.yaml

``` yaml
students: 
    Atsushi: 
        sex: male
    Honoka: 
        sex: female
teachers:
    Jun: 
        sex: male
    Riko: 
        sex: female
```

students/Atsushi.yaml

``` yaml
    sex: male
```

students/Honoka.yaml

``` yaml
    sex: female
```

teachers/Jun.yaml

``` yaml
    sex: male
```

teachers/Riko.yaml

``` yaml
    sex: female
```
